<?php
// $Id$

/**
 * @file
 * Demonstrates use of the Form API. Test text.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 */

/**
 * Implements hook_menu().
 */
function input_menu() {
  $items['input/examples'] = array(
    'title' => 'Form API examples',
    'description' => 'Example of using the Form API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('input_simple_form'),
    'access callback' => TRUE,
  );
  $items['admin/pos/orders'] = array(
		'title' => 'Таблица заказов',
		'description' => 'Orders management page.',
		'page callback' => 'pos_system_orders',
		'type' => MENU_CALLBACK,
		'weight' => -10,
		//'access callback' => TRUE,
		'access callback' => 'user_access',
		'access arguments' => array('create bookable_product content'),
	);
  return $items;
}




/**
 * A simple form.
 */
function input_simple_form($form, &$form_submit) {
  $form['color'] = array(
    '#title' => t('Favorite color'),
       '#required' => TRUE,
    '#description' => t('What is your favorite color? Blue? No, wait-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}